store/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, IntegerField, DecimalField
from wtforms.validators import InputRequired



class CreateItem(FlaskForm):
    name = StringField(validators = [InputRequired()])
    price = DecimalField(validators = [InputRequired()])
    stock = IntegerField(validators = [InputRequired()])
    submit = SubmitField('create')


class RestockItems(FlaskForm):
    addition = IntegerField(validators=[InputRequired()])
    submit = SubmitField('Confirm Restock')


class ModifyItem(FlaskForm):
    submit = SubmitField('apply')

store/main/__init__.py
"""Application main blueprint"""

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

store/main/views.py
from flask import render_template, url_for, redirect, request, flash, current_app
from . import main
from .. import db
from .forms import CreateItem, RestockItems
from ..models import Item, CartRow



@main.route('/favicon.ico')
def favicon():
    """Adding a favicon to the app"""
    return current_app.send_static_file('img/favicon.ico')


def filter_low_stock(items):
    return [item for item in items if item.low_stock]


@main.route('/', methods=['GET', 'POST'])
def index():
    items = Item.query.all()
    low_stock_items = filter_low_stock(items)

    if request.method == 'POST':
        # take the form's ID and quantity fields
        id = int(request.form.get('id'))
        quantity = int(request.form.get('quantity'))

        # prevent invalid entries
        if quantity <= 0:
            flash('⚠ Please enter a valid purchase quantity', 'misc')
            return redirect(url_for('.index'))

        # query id from both tables
        item = Item.query.get(id)
        cart_product = CartRow.query.get(id)
        
        # item exists in the cart
        if cart_product:
            if (quantity + cart_product.purchase_quantity) > item.stock:
                flash('⚠ Insufficient quantity in stock', 'misc')
                return redirect(url_for('.index'))
            cart_product.purchase_quantity += quantity
            cart_product.calculate_sub_total(item.price)
            db.session.add(cart_product)
            flash('ℹ {}\'s purchase quantity increased'.format(item.name), 'info')
        # item does not exist in the cart
        else:
            if quantity > item.stock:
                flash('⚠ Insufficient quantity in stock', 'misc')
                return redirect(url_for('.index'))
            # create cart item from above data and add to DB session and commit
            cart_row = CartRow(id = id,
                                name = item.name,
                                purchase_quantity = quantity,
                                sub_total = quantity * item.price)
            db.session.add(cart_row)
            flash('ℹ {} added to cart'.format(item.name), 'info')
        db.session.commit()
        return redirect(url_for('.index'))
    
    if low_stock_items:
        flash('⚠ Some items are low on stock. Please restock as soon as possible ⚠', 'warning')
    return render_template('main/home.html', items = items)


@main.route('/cart', methods=['GET', 'POST'])
def cart():
    cart_rows = CartRow.query.all()
    cart_total = sum([row.sub_total for row in cart_rows])

    if request.method == 'POST':
        row_ids = request.form.getlist('remove_item')

        # no items are selected for deletion
        if row_ids == []:
            # cart table contains items, proceed to checkout
            if cart_rows:
                """Confirm checkout logic. 
                
                Basically applies purchase quantities and updates item stock counts, then proceeds to empty cart table"""
                for row in cart_rows:
                    # query respective items
                    item = Item.query.get(row.id)
                    # apply purchase to stock
                    item.stock -= row.purchase_quantity
                    item.verify_stock_status()
                    # update item in DB
                    db.session.add(item)
                
                # empty cart table
                for row in cart_rows:
                    db.session.delete(row)

                # commit session and redirect
                db.session.commit()
                flash('Checkout Complete! Return to Store Front ✔🧾', 'success')
                return redirect(url_for('.cart'))
            else:
                flash('Cart is empty 🛒✖', 'error')
                return redirect(url_for('.cart'))
        else:
            """Delete items from cart"""
            # loop though list and delete each item from DB
            for row in row_ids:
                cart_row = CartRow.query.get(int(row))
                db.session.delete(cart_row)
            db.session.commit()
            return redirect(url_for('.cart'))

    return render_template('main/cart.html', cart_rows = cart_rows, cart_total = cart_total)


@main.route('/create', methods=['GET', 'POST'])
def create_item():
    items = Item.query.all()
    # most recent item ID
    if items == []:
        next_id = 1
    else:
        next_id = [x.id for x in items][-1] + 1

    create = CreateItem()
    if create.validate_on_submit():
        # ensure user enter valid stock amount
        if create.stock.data < 0 or create.price.data < 0:
            flash('Invalid stock or price amount', 'error')
            return redirect(url_for('.create_item'))
        item = Item(id = next_id, 
                    name = create.name.data,
                    price = create.price.data,
                    stock = create.stock.data,
                    post_restock = create.stock.data)
        item.verify_stock_status()
        db.session.add(item)
        db.session.commit()
        flash('Item successfully added ✔', 'success')
        return redirect(url_for('.create_item'))
    return render_template('main/create.html', create = create)


@main.route('/restock', methods=['GET', 'POST'])
def restock():
    items = Item.query.all()
    low_stock_items = filter_low_stock(items)
    item_names = [x.name for x in items]
    modded_item = None
    restock_form = RestockItems()

    if restock_form.validate_on_submit():
        name = request.form.get('item-name').strip()
        addition = restock_form.addition.data

        # ensure user does not restock a negative number
        if addition < 1 or name not in item_names:
            flash('Sorry, you have entered an invalid stock amount ❌', 'error')
            return redirect(url_for('.restock'))

        for item in items:
            if item.name == name:
                modded_item = item
                break

        modded_item.restock(addition)
        db.session.add(modded_item)
        db.session.commit()
        flash('ℹ {} {} added to stock'.format(addition, item.name), 'info')
        return redirect(url_for('.restock'))

    if low_stock_items:
        flash('⚠ Kindly restock the following items:', 'warning')
    return render_template('main/restock.html', items = items, restock_form = restock_form, low_stock_items = low_stock_items)


@main.route('/manage_items', methods=['GET', 'POST'])
def manage_items():
    items = Item.query.all()
    low_stock_items = filter_low_stock(items)

    if request.method == 'POST':
        # item(s) selected for deletion
        selected_ids = request.form.getlist('delete')
        if selected_ids != []:
            to_be_removed = [Item.query.get(id) for id in selected_ids]
            for item in to_be_removed:
                db.session.delete(item)
            db.session.commit()
            flash('Item(s) removed ✔', 'success')
            return redirect(url_for('.manage_items'))
        # if no items selected, check if a modification was made
        else:
            item_id = (request.form.get('item_id'))

            # either form has been submitted incorrectly
            if item_id is None:
                flash('No action was performed', 'misc')
                return redirect(url_for('.manage_items'))
            modded_stock = int(request.form.get('modded_stock'))
            modded_price = request.form.get('modded_price')

            # prevent invalid entiries
            try:
                modded_price = float(modded_price)
            except ValueError:
                flash('Invalid entry ❌', 'error')
                return redirect(url_for('.manage_items'))

            # query item
            item = Item.query.get(item_id)
            old_details = (item.price, item.stock)
            # check if no changes were made
            if item.price == modded_price and item.stock == modded_stock:
                flash('⚠ No changes were made', 'misc') 
                return redirect(url_for('.manage_items'))
            else:
                # make changes otherwise
                modded_item = item
                modded_item.price = modded_price
                modded_item.stock = modded_stock
                modded_item.post_restock = modded_stock
                modded_item.verify_stock_status()

                # add to DB and commit
                db.session.add(modded_item)
                db.session.commit()
                flash('ℹ Changes applied to {}:'.format(item.name), 'info')
                # if price was changed
                if old_details[0] != modded_price:
                    flash('\tPrice change [ NGN {:,} to NGN {:,} ]'.format(old_details[0], modded_price), 'info')
                # if stock was changed
                if old_details[1] != modded_stock:
                    flash('\tStock change [ {} to {} ]'.format(old_details[1], modded_stock), 'info')
                return redirect(url_for('.manage_items'))

    if low_stock_items:
        flash('⚠ Some items are low on stock. Please restock as soon as possible ⚠', 'warning')
    return render_template('main/manage.html', items = items)

store/templates/main/create.html
{% extends "base.html" %}

{% block title %}Create New Item{% endblock %}

{% block body %}
<div class="menu">
    <a href="{{ url_for('main.index') }}" class="menu-item btn"><svg fill="#000000" viewBox="0 0 32 32" width="32px" height="32px"><path fill="none" stroke="#000000" stroke-miterlimit="10" stroke-width="2" d="M3 17L16 4 29 17"/><path fill="none" stroke="#000000" stroke-miterlimit="10" stroke-width="2" d="M6 14L6 27 13 27 13 17 19 17 19 27 26 27 26 14"/></svg>Store Front</a>

    <a href="{{ url_for('main.create_item') }}" class="menu-item btn active"><svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 32 32" width="32px" height="32px"><path d="M 16 3 C 8.832031 3 3 8.832031 3 16 C 3 23.167969 8.832031 29 16 29 C 23.167969 29 29 23.167969 29 16 C 29 8.832031 23.167969 3 16 3 Z M 16 5 C 22.085938 5 27 9.914063 27 16 C 27 22.085938 22.085938 27 16 27 C 9.914063 27 5 22.085938 5 16 C 5 9.914063 9.914063 5 16 5 Z M 15 10 L 15 15 L 10 15 L 10 17 L 15 17 L 15 22 L 17 22 L 17 17 L 22 17 L 22 15 L 17 15 L 17 10 Z"/></svg>Create New Item</a>

    <a href="{{ url_for('main.restock') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 32 32" width="32px" height="32px"><path d="M 23.90625 3.96875 C 22.859375 3.96875 21.8125 4.375 21 5.1875 L 5.1875 21 L 5.125 21.3125 L 4.03125 26.8125 L 3.71875 28.28125 L 5.1875 27.96875 L 10.6875 26.875 L 11 26.8125 L 26.8125 11 C 28.4375 9.375 28.4375 6.8125 26.8125 5.1875 C 26 4.375 24.953125 3.96875 23.90625 3.96875 Z M 23.90625 5.875 C 24.410156 5.875 24.917969 6.105469 25.40625 6.59375 C 26.378906 7.566406 26.378906 8.621094 25.40625 9.59375 L 24.6875 10.28125 L 21.71875 7.3125 L 22.40625 6.59375 C 22.894531 6.105469 23.402344 5.875 23.90625 5.875 Z M 20.3125 8.71875 L 23.28125 11.6875 L 11.1875 23.78125 C 10.53125 22.5 9.5 21.46875 8.21875 20.8125 Z M 6.9375 22.4375 C 8.136719 22.921875 9.078125 23.863281 9.5625 25.0625 L 6.28125 25.71875 Z"/></svg>Restock Items</a>

    <a href="{{ url_for('main.manage_items') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 7 4 L 7 5 L 8 5 L 8 4 Z M 7 6 L 7 11 L 8 11 L 8 6 Z"/></svg>Inventory</a>
</div>

<hr>

<div class="container">
    <h1>Create Item</h1>

    <form method="POST">
        {{ create.hidden_tag() }}
        <table class="u-full-width">
            <caption>Add a new item to the inventory</caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Stock</th>
                    <th></th>
                </tr>
            </thead>
            
            <tbody>
                <tr>
                    <td>{{ create.name(placeholder='Item Name') }}</td>
                    <td>{{ create.price(placeholder='Price') }}</td>
                    <td>{{ create.stock(placeholder='Stock') }}</td>
                    <td>{{ create.submit(class='confirm active') }}</td>
                </tr>
            </tbody>
        </table>

        {% for categ, msg in get_flashed_messages(with_categories=True) %}
        <div class="flash">
            <li style="list-style: none;" class="{{ categ }}">{{ msg }}</li>
        </div>
        {% endfor %}
    </form>
</div>

{% endblock %}

store/templates/main/home.html
{% extends "base.html" %}

{% block title %}NDA Minimart{% endblock %}

{% block body %}

<div class="menu">
    <a href="{{ url_for('main.index') }}" class="menu-item btn active"><svg fill="#ffffff" viewBox="0 0 32 32" width="32px" height="32px"><path fill="none" stroke="#ffffff" stroke-miterlimit="10" stroke-width="2" d="M3 17L16 4 29 17"/><path fill="none" stroke="#ffffff" stroke-miterlimit="10" stroke-width="2" d="M6 14L6 27 13 27 13 17 19 17 19 27 26 27 26 14"/></svg>Store Front</a>

    <a href="{{ url_for('main.create_item') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 32 32" width="32px" height="32px"><path d="M 16 3 C 8.832031 3 3 8.832031 3 16 C 3 23.167969 8.832031 29 16 29 C 23.167969 29 29 23.167969 29 16 C 29 8.832031 23.167969 3 16 3 Z M 16 5 C 22.085938 5 27 9.914063 27 16 C 27 22.085938 22.085938 27 16 27 C 9.914063 27 5 22.085938 5 16 C 5 9.914063 9.914063 5 16 5 Z M 15 10 L 15 15 L 10 15 L 10 17 L 15 17 L 15 22 L 17 22 L 17 17 L 22 17 L 22 15 L 17 15 L 17 10 Z"/></svg>Create New Item</a>

    <a href="{{ url_for('main.restock') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 32 32" width="32px" height="32px"><path d="M 23.90625 3.96875 C 22.859375 3.96875 21.8125 4.375 21 5.1875 L 5.1875 21 L 5.125 21.3125 L 4.03125 26.8125 L 3.71875 28.28125 L 5.1875 27.96875 L 10.6875 26.875 L 11 26.8125 L 26.8125 11 C 28.4375 9.375 28.4375 6.8125 26.8125 5.1875 C 26 4.375 24.953125 3.96875 23.90625 3.96875 Z M 23.90625 5.875 C 24.410156 5.875 24.917969 6.105469 25.40625 6.59375 C 26.378906 7.566406 26.378906 8.621094 25.40625 9.59375 L 24.6875 10.28125 L 21.71875 7.3125 L 22.40625 6.59375 C 22.894531 6.105469 23.402344 5.875 23.90625 5.875 Z M 20.3125 8.71875 L 23.28125 11.6875 L 11.1875 23.78125 C 10.53125 22.5 9.5 21.46875 8.21875 20.8125 Z M 6.9375 22.4375 C 8.136719 22.921875 9.078125 23.863281 9.5625 25.0625 L 6.28125 25.71875 Z"/></svg>Restock Items</a>

    <a href="{{ url_for('main.manage_items') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 7 4 L 7 5 L 8 5 L 8 4 Z M 7 6 L 7 11 L 8 11 L 8 6 Z"/></svg>Inventory</a>
</div>

<hr>

<div class="container">
    <h1>Store Front</h1>

    <div class="center-button">
        <input type="text" onkeyup="search()" placeholder="Search for an item..." id="searchBtn">
    </div>
    
    <table class="u-full-width">
        <caption>Add items to cart</caption>
        <thead>
            <tr>
                <th style="width: 10%;">ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Available Stock</th>
                <th style="width: 15%;">Purchase Quantity</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {% for item in items %}
            <tr class="item-row {{ item.name }}">
                <form method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                    <td><input type="text" name="id" value="{{ item.id }}" style="width: 100%;" readonly></td>
                    <td class="item-name">{{ item.name }}</td>
                    <td>NGN {{ '{:,}'.format(item.price) }}</td>

                    {% if item.low_stock and not item.sold_out %}
                    <td class="misc">{{ item.stock }}</td>
                    {% elif item.sold_out %}
                    <td style="font: small-caps;" class="error">SOLD OUT</td>
                    {% else %}
                    <td>{{ item.stock }}</td>
                    {% endif %}

                    {% if item.sold_out %}
                    <td><input type="number" style="width: 100%;" value="-" name="quantity" disabled></td>
                    <td><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 8.839844 12.519531 10.066406 11.726563 11.019531 L 3.980469 3.273438 C 4.933594 2.480469 6.160156 2 7.5 2 Z M 3.273438 3.980469 L 11.019531 11.726563 C 10.066406 12.519531 8.839844 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 6.160156 2.480469 4.933594 3.273438 3.980469 Z"/></svg></td>
                    {% else %}
                    <td><input type="number" style="width: 100%;" value="0" name="quantity"></td>
                    <td><input type="submit" class="confirm active" value="Add"></td>
                    {% endif %}
                </form>
            </tr>
            {% endfor %}
        </tbody>

        {% for categ, msg in get_flashed_messages(with_categories=True) %}
        <div class="flash">
            <li style="list-style: none;" class="{{ categ }}">{{ msg }}</li>
        </div>
        {% endfor %}
    </table>

    <h3>
        <a href="{{ url_for('main.cart') }}" class="menu-item cart" style="color: black; text-decoration: none;">
            <img src="{{ url_for('static', filename='img/shopping-cart.png') }}" alt="cart-icon" class="img-icon">
            Checkout ➡
        </a>
    </h3>
    
</div>

{% endblock %}

store/templates/main/manage.html
{% extends "base.html" %}

{% block title %}Manage Inventory{% endblock %}

{% block body %}

<div class="menu">
    <a href="{{ url_for('main.index') }}" class="menu-item btn"><svg fill="#000000" viewBox="0 0 32 32" width="32px" height="32px"><path fill="none" stroke="#000000" stroke-miterlimit="10" stroke-width="2" d="M3 17L16 4 29 17"/><path fill="none" stroke="#000000" stroke-miterlimit="10" stroke-width="2" d="M6 14L6 27 13 27 13 17 19 17 19 27 26 27 26 14"/></svg>Store Front</a>

    <a href="{{ url_for('main.create_item') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 32 32" width="32px" height="32px"><path d="M 16 3 C 8.832031 3 3 8.832031 3 16 C 3 23.167969 8.832031 29 16 29 C 23.167969 29 29 23.167969 29 16 C 29 8.832031 23.167969 3 16 3 Z M 16 5 C 22.085938 5 27 9.914063 27 16 C 27 22.085938 22.085938 27 16 27 C 9.914063 27 5 22.085938 5 16 C 5 9.914063 9.914063 5 16 5 Z M 15 10 L 15 15 L 10 15 L 10 17 L 15 17 L 15 22 L 17 22 L 17 17 L 22 17 L 22 15 L 17 15 L 17 10 Z"/></svg>Create New Item</a>

    <a href="{{ url_for('main.restock') }}" class="menu-item btn"><svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 32 32" width="32px" height="32px"><path d="M 23.90625 3.96875 C 22.859375 3.96875 21.8125 4.375 21 5.1875 L 5.1875 21 L 5.125 21.3125 L 4.03125 26.8125 L 3.71875 28.28125 L 5.1875 27.96875 L 10.6875 26.875 L 11 26.8125 L 26.8125 11 C 28.4375 9.375 28.4375 6.8125 26.8125 5.1875 C 26 4.375 24.953125 3.96875 23.90625 3.96875 Z M 23.90625 5.875 C 24.410156 5.875 24.917969 6.105469 25.40625 6.59375 C 26.378906 7.566406 26.378906 8.621094 25.40625 9.59375 L 24.6875 10.28125 L 21.71875 7.3125 L 22.40625 6.59375 C 22.894531 6.105469 23.402344 5.875 23.90625 5.875 Z M 20.3125 8.71875 L 23.28125 11.6875 L 11.1875 23.78125 C 10.53125 22.5 9.5 21.46875 8.21875 20.8125 Z M 6.9375 22.4375 C 8.136719 22.921875 9.078125 23.863281 9.5625 25.0625 L 6.28125 25.71875 Z"/></svg>Restock Items</a>

    <a href="{{ url_for('main.manage_items') }}" class="menu-item btn active"><svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 16 16" width="32px" height="32px"><path d="M 7.5 1 C 3.917969 1 1 3.917969 1 7.5 C 1 11.082031 3.917969 14 7.5 14 C 11.082031 14 14 11.082031 14 7.5 C 14 3.917969 11.082031 1 7.5 1 Z M 7.5 2 C 10.542969 2 13 4.457031 13 7.5 C 13 10.542969 10.542969 13 7.5 13 C 4.457031 13 2 10.542969 2 7.5 C 2 4.457031 4.457031 2 7.5 2 Z M 7 4 L 7 5 L 8 5 L 8 4 Z M 7 6 L 7 11 L 8 11 L 8 6 Z"/></svg>Inventory</a>
</div>

<hr>

<div class="container u-full-width">
    <h1>Inventory Management</h1>

    <div class="center-button">
        <input type="text" onkeyup="search()" placeholder="Search for an item..." id="searchBtn">
    </div>

    {% for categ, msg in get_flashed_messages(with_categories=True) %}
    <div class="flash">
        <li style="list-style: none;" class="{{ categ }}">{{ msg }}</li>
    </div>
    {% endfor %}

    <input type="button" value="Modify Items 🖊" class="modify-btn active" onclick="modifyItems()">
    <input type="button" value="Remove Items 🚮" class="remove-btn active" onclick="modifyItems()">

    {% if items == [] %}
    <h3>Inventory is empty 😟 <a href="{{ url_for('main.create_item') }}">Create a new item</a> and see it appear here.</h3>

    {% else %}

    <div class="remove-items" style="display: none;">
        <form method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <table class="u-full-width">
                <caption>Delete Inventory Items</caption>
                <thead>
                    <tr>
                        <th>Item Name</th>
                        <th>Price</th>
                        <th>Available Stock</th>
                        <th></th>
                    </tr>
                </thead>
    
                <tbody>
                    {% for item in items %}
                    <tr class="item-row {{ item.name }}">
                        <td>{{ item.name }}</td>
                        <td>NGN {{ '{:,}'.format(item.price) }}</td>
                        <td>{{ item.stock }}</td>
                        <td><input class="pointer" type="checkbox" name="delete" value="{{ item.id }}"></td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>

            <div class="center-button">
                <input type="submit" value="Delete Items" class="delete remove">
            </div>
        </form>
    </div>


    <div class="modify-items">
        <table class="u-full-width">
            <caption>Modify An Item</caption>
            <thead>
                <tr>
                    <th style="width: 10%;">ID</th>
                    <th>Item Name</th>
                    <th>Price</th>
                    <th style="width: 15%;">Available Stock</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                {% for item in items %}
                <tr class="item-row {{ item.name }}">
                    <form method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                        <td><input type="text" style="width: 100%;" name="item_id" value="{{ item.id }}" readonly></td>
                        <td><input type="text" value="{{ item.name }}" readonly></td>
                        <td>NGN <input type="text" name="modded_price" value="{{ item.price }}"></td>
                        <td><input type="number" style="width: 100%;" name="modded_stock" value="{{ item.stock }}"></td>
                        <td><input type="submit" value="Apply" class="confirm active"></td>
                    </form>
                </tr>
                {% endfor %} 
            </tbody>
        </table>
    </div>    
    {% endif %}
</div>

{% endblock %}